export const GET_TOKEN = 'GET_TOKEN'
export const SAVE_INFO= 'SAVE_INFO'
 export const UPDATE_HISTORY='UPDATE_HISTORY'
 export const UPDATE_LOVELIST='UPDATE_LOVELIST'
 export const GET_LOVELIST=`GET_LOVELIST`
 export const UNADD_LOVELIST='UNADD_LOVELIST'
 